# Day Objectives
## Numpy

**Sorting Arrays :**
- sort
- sort(axis =0)



**Array Manipulation :**
- Transposing
- changing shape (ravel & reshape)
- adding/ removing elemnts
    - append
    - insert
    - delete
- Combining array
    - concatenate
    - hstack
    - vstack
    - ravel
    - flatten
    
**Saving & Loading files :**
- save('file_name', array)
- load('file_name.npy')


In [1]:
import numpy as np

In [22]:
n1 = np.array([[2,3,2,4],[5,6,3,7],[8,6,9,6]])
n1

array([[2, 3, 2, 4],
       [5, 6, 3, 7],
       [8, 6, 9, 6]])

In [23]:
n1.shape

(3, 4)

In [24]:
n1.ndim

2

In [21]:
n1.dtype

dtype('<U11')

In [ ]:
# Priority order of datatypes : str, Complex, float, int

# Sorting Arrays 

In [28]:
n1.sort(axis = 0) # rows
n1

array([[2, 2, 3, 4],
       [3, 5, 6, 7],
       [6, 6, 8, 9]])

In [29]:
n1.sort(axis = 1) # columns
n1

array([[2, 2, 3, 4],
       [3, 5, 6, 7],
       [6, 6, 8, 9]])

# Array Manipulation 
Transposing
changing shape (ravel & reshape)
adding/ removing elemnts
append
insert
delete
Combining array
concatenate
hstack
vstack
ravel
flatten

In [30]:
n1

array([[2, 2, 3, 4],
       [3, 5, 6, 7],
       [6, 6, 8, 9]])

In [31]:
n1.T

array([[2, 3, 6],
       [2, 5, 6],
       [3, 6, 8],
       [4, 7, 9]])

In [32]:
np.transpose(n1)

array([[2, 3, 6],
       [2, 5, 6],
       [3, 6, 8],
       [4, 7, 9]])

In [33]:
# changing shape
n1.shape 
# 3*4 = 12, factors 1,2,3,4,6,12

(3, 4)

In [34]:
n1.reshape(6,2)

array([[2, 2],
       [3, 4],
       [3, 5],
       [6, 7],
       [6, 6],
       [8, 9]])

In [35]:
n1.reshape(1,12)

array([[2, 2, 3, 4, 3, 5, 6, 7, 6, 6, 8, 9]])

In [39]:
n1.reshape(3,2,2,1) # by using reshape, can change any D

array([[[[2],
         [2]],

        [[3],
         [4]]],


       [[[3],
         [5]],

        [[6],
         [7]]],


       [[[6],
         [6]],

        [[8],
         [9]]]])

In [40]:
# adding/ removing elemnts
np.add(n1,n1)

array([[ 4,  4,  6,  8],
       [ 6, 10, 12, 14],
       [12, 12, 16, 18]])

In [42]:
np.subtract(n1,n1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [44]:
np.append(n1, 100)

array([  2,   2,   3,   4,   3,   5,   6,   7,   6,   6,   8,   9, 100])

In [48]:
np.insert(n1,5,1000)

array([   2,    2,    3,    4,    3, 1000,    5,    6,    7,    6,    6,
          8,    9])

In [54]:
np.delete(n1,5)

array([2, 2, 3, 4, 3, 6, 7, 6, 6, 8, 9])

In [55]:
del n1

In [57]:
n1

NameError: name 'n1' is not defined

In [71]:
n2 = np.array([1,2,3,4,5,56,6,76,5,7,8,0])
n2 = n2.reshape(3,-1)
n2

array([[ 1,  2,  3,  4],
       [ 5, 56,  6, 76],
       [ 5,  7,  8,  0]])

In [76]:
np.concatenate(n2)

array([ 1,  2,  3,  4,  5, 56,  6, 76,  5,  7,  8,  0])

In [75]:
n2

array([[ 1,  2,  3,  4],
       [ 5, 56,  6, 76],
       [ 5,  7,  8,  0]])

In [77]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

In [78]:
n3 = np.array([[2,3,4,5],[5,3,7,6]])
n3

array([[2, 3, 4, 5],
       [5, 3, 7, 6]])

In [81]:
np.concatenate([n2,n3], axis = 0)

array([[ 1,  2,  3,  4],
       [ 5, 56,  6, 76],
       [ 5,  7,  8,  0],
       [ 2,  3,  4,  5],
       [ 5,  3,  7,  6]])

In [82]:
np.concatenate([n2,n3], axis = 1) 

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [86]:
n2

array([[ 1,  2,  3,  4],
       [ 5, 56,  6, 76],
       [ 5,  7,  8,  0]])

In [84]:
np.hstack(n2) # entire array is converted into 1-D

array([ 1,  2,  3,  4,  5, 56,  6, 76,  5,  7,  8,  0])

In [93]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    hstack

In [98]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [99]:
# ravel
#flatten
np.ravel(n2)

array([ 1,  2,  3,  4,  5, 56,  6, 76,  5,  7,  8,  0])

In [100]:
n2.flatten()

array([ 1,  2,  3,  4,  5, 56,  6, 76,  5,  7,  8,  0])

In [101]:
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [102]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    vstack : Stac

# Saving & Loading files :

save('file_name', array)

load('file_name.npy')

In [103]:
n2

array([[ 1,  2,  3,  4],
       [ 5, 56,  6, 76],
       [ 5,  7,  8,  0]])

In [104]:
np.save("sample",n2)

In [105]:
np.load("sample.npy")

array([[ 1,  2,  3,  4],
       [ 5, 56,  6, 76],
       [ 5,  7,  8,  0]])